import { Link } from 'react-router-dom'
import SEO from '../components/SEO'

const sections = [
  {
    h: '1. Acceptance of Terms',
    p: [
      'By accessing or using this website, you agree to be bound by these Terms of Use and our Privacy Policy. If you do not agree with any part of these terms, please do not use this website.',
    ],
  },
  {
    h: '2. No Offer of Insurance',
    p: [
      'Nothing on this website constitutes an offer to sell insurance, a binding quote, or a contract of insurance. All quotes and estimates generated by the tools on this site are illustrative only.',
      'Actual premiums, terms, and coverage availability are determined solely by the issuing insurance carrier based on complete underwriting of your application, health history, and other factors.',
    ],
  },
  {
    h: '3. Not Financial or Legal Advice',
    p: [
      'Content on this website — including articles in our Education Center and results from our calculators — is provided for general informational purposes only. It does not constitute financial, legal, tax, or investment advice.',
      'You should consult a licensed professional regarding your specific situation before making any financial decision.',
    ],
  },
  {
    h: '4. Accuracy of Information',
    p: [
      'We work to keep the information on this website accurate and current, but we make no warranties or representations as to its completeness or accuracy. Product features, rates, and carrier offerings change frequently.',
      'Insurance products may not be available in all states. Licensing information for Buckalew Financial Services is available upon request.',
    ],
  },
  {
    h: '5. Intellectual Property',
    p: [
      'All content on this website — including text, graphics, logos, and design — is the property of Buckalew Financial Services or its licensors and may not be reproduced without written permission.',
      'Photography used on this website is licensed through third-party stock providers and remains subject to their license terms.',
    ],
  },
  {
    h: '6. Third-Party Links & Services',
    p: [
      'This website may contain links to third-party websites (such as Google Maps) or use third-party services (such as form processing and analytics providers). We are not responsible for the content or privacy practices of those third parties.',
    ],
  },
  {
    h: '7. Limitation of Liability',
    p: [
      'To the fullest extent permitted by law, Buckalew Financial Services shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of this website or reliance on any information contained herein.',
    ],
  },
  {
    h: '8. Governing Law',
    p: [
      'These Terms of Use are governed by the laws of the State of Florida, without regard to conflict-of-law principles.',
    ],
  },
]

export default function Terms() {
  return (
    <>
      <SEO
        title="Terms of Use | Buckalew Financial Services"
        description="Terms governing use of the Buckalew Financial Services website, including disclaimers about quotes, estimates, and the information provided."
        path="/terms"
      />
      <section className="page-hero">
        <div className="container">
          <div className="breadcrumb"><Link to="/">Home</Link> / Terms of Use</div>
          <h1>Terms of Use</h1>
          <p>Effective date: January 1, 2026 · Last updated: August 2026</p>
        </div>
      </section>

      <section className="section" style={{ paddingTop: 48 }}>
        <div className="container article-body">
          {sections.map((s) => (
            <div key={s.h}>
              <h2>{s.h}</h2>
              {s.p.map((para, i) => <p key={i}>{para}</p>)}
            </div>
          ))}
          <p style={{ marginTop: 30 }}>
            Questions? Contact us at{' '}
            <a href="mailto:hello@buckalewfinancial.com" style={{ color: 'var(--gold-500)' }}>
              hello@buckalewfinancial.com
            </a>{' '}
            or <b>(813) 863-5917</b>. See also our{' '}
            <Link to="/privacy-policy" style={{ color: 'var(--gold-500)' }}>Privacy Policy</Link>.
          </p>
        </div>
      </section>
    </>
  )
}